package com.offcn.wechat.bean

case class UserTable (topicType: String,
					  entityId: String,
					  entityTyp: String,
					  sells_id: String,
					  id:String,
					  androidVersion: String,
					  area: String,
					  areas: String,
					  corpid: String,
					  departme: String,
					  deviceBrand: String,
					  headImg:String,
					  imei:String,
					  isRoot:Boolean,
					  jobList:String,
					  mobile:String,
					  nick:String,
					  operateType:Int,
					  parents:String,
					  parentsHistory:String,
					  realnam:String,
					  remark:String,
					  remarks: String,
					  softVersion: String,
					  systemModel: String,
					  systemVersion: String,
					  wxtype: String,
					  wx_name: String
					 )
